name: Check source code

on:
  push:
    branches:
      - "master"
      - "next"

    paths:
      - "src/**"

  pull_request:
    branches:
      - "master"
      - "next"

    paths:
      - "src/**"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check source code
        run: |
          nix develop
          cargo check --verbose