name: Check source code

on:
  push:
    branches:
      - master
      - next

    paths:
      - "src/**"

  pull_request:
    branches:
      - master
      - next

    paths:
      - "src/**"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check_source_code:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:devel

      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Install build dependencies
        run: |
          apt update
          apt install -y git curl build-essential libgtk-4-dev libadwaita-1-dev

      - name: Install runtime dependencies
        run: |
          apt update
          apt install -y tar zip p7zip-full

      - name: Download rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check source code
        run: cargo check --verbose

      - name: Perform source code tests
        run: cargo test --verbose
