name: Compile release build

on:
  push:
    branches:
      - master

    paths:
      - "src/**"

  release:
    types:
      - published

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile_ubuntu_build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:devel

      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Install build dependencies
        run: |
          apt update
          apt install -y git curl build-essential libgtk-4-dev libadwaita-1-dev

      - name: Download rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Compile release build
        run: cargo build --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-native-build
          path: target/release/anime-games-launcher
